### ISSUE TITLE
TypeError: Cannot read property 'success' of undefined

### ISSUE THREAD

**Issue by astromac** [rogeriopvl/gulp-jsonlint#62]
### Snippet from gulpfile.js
```
const jsonlint = require('gulp-jsonlint');

gulp.task('lintjson', () => {
  gulp.src(['/*.json', '.babelrc', '.csslintrc', '.eslintrc', '.tern-project'])
    .pipe(jsonlint())
    .pipe(jsonlint.failOnError())
    .on('error', onError);
});
```
### Error output
```
/Users/chris/Sites/puretable/node_modules/gulp-jsonlint/index.js:64
        if (file.jsonlint.success === false) {
                         ^

TypeError: Cannot read property 'success' of undefined
    at DestroyableTransform._transform (/Users/chris/Sites/puretable/node_modules/gulp-jsonlint/index.js:64:26)
    at DestroyableTransform.Transform._read (/Users/chris/Sites/puretable/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/chris/Sites/puretable/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/chris/Sites/puretable/node_modules/readable-stream/lib/_stream_writable.js:337:64)
    at writeOrBuffer (/Users/chris/Sites/puretable/node_modules/readable-stream/lib/_stream_writable.js:326:5)
    at DestroyableTransform.Writable.write (/Users/chris/Sites/puretable/node_modules/readable-stream/lib/_stream_writable.js:263:11)
    at Transform.ondata (_stream_readable.js:626:20)
    at emitOne (events.js:115:13)
    at Transform.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Transform.Readable.push (_stream_readable.js:195:10)
    at Transform.push (_stream_transform.js:151:32)
    at afterTransform (_stream_transform.js:100:12)
    at TransformState.afterTransform (_stream_transform.js:75:12)
    at Transform.util.transform [as _transform] (/Users/chris/Sites/puretable/node_modules/gulp-eslint/index.js:70:3)
```

**Comment by ChrisBFusion** [comment]
Never mind. New to Gulp.

**Comment by astromac** [comment]
Never mind. I'm new to Gulp.
